"""empty message

Revision ID: 5d916343122f
Revises: 
Create Date: 2025-07-20 10:50:06.097741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d916343122f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrusted_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('___client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_furigana', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('intention_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('entrusted_book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrusted_book_id'], ['entrusted_book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amount_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Integer(), nullable=False),
    sa.Column('entrusted_book_name', sa.String(length=255), nullable=False),
    sa.Column('has_stamp', sa.Boolean(), nullable=True),
    sa.Column('apply_consumption_tax', sa.Boolean(), nullable=True),
    sa.Column('apply_withholding', sa.Boolean(), nullable=True),
    sa.Column('advance_payment', sa.Integer(), nullable=True),
    sa.Column('reward_amounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expense_amounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('item_types', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['___client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amount_document')
    op.drop_table('___client')
    op.drop_table('entrusted_book')
    # ### end Alembic commands ###
