"""Rename property_name to name in entrusted_book

Revision ID: cafb6884a934
Revises: 5d916343122f
Create Date: 2025-07-22 10:49:16.335619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafb6884a934'
down_revision = '5d916343122f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrusted_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.drop_column('property_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrusted_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
